# Generated by Django 4.2.5 on 2023-09-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_candidate_token_alter_userprofile_role_and_more'),
        ('talentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.candidate'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
